spring:
  application:
    name: CHAT-SERVICE
  data:
    mongodb:
      uri: "mongodb+srv://21522343:hoangminhdeptrai@cluster0.06mhzjg.mongodb.net/?retryWrites=true&w=majority"
      database: "CDM"

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761