sentry:
  dsn: https://1a77d0e3661b7a8d09ad9f62509c240a@o4507334562938880.ingest.de.sentry.io/4507345724702800
  traces-sample-rate: 1.0

server:
  port: 0

spring:
  data:
    mongodb:
      uri: "mongodb+srv://21522343:hoangminhdeptrai@cluster0.06mhzjg.mongodb.net/?retryWrites=true&w=majority"
      database: "CDM"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: INVENTORY-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}


management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0