spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}


server:
    port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0