sentry:
  dsn: https://1a77d0e3661b7a8d09ad9f62509c240a@o4507334562938880.ingest.de.sentry.io/4507345724702800
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}


server:
    port: 0

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0