server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: REGISTRY-SERVICE

sentry:
  dsn: https://1ab8f67e33fe02b6b29cbd558dcd4572@o4507334562938880.ingest.de.sentry.io/4507345638719568
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
