sentry:
  dsn: https://d51c408cc314b31d3c624370d58fe8ba@o4507395230138368.ingest.de.sentry.io/4507395256877136
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          username: dvcminh
          password: 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
          uri: https://github.com/dvcminh/cdmconfig
          default-label: main
          clone-on-start: true

